<?xml version="1.0"?>
<robot name="robotic" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- <xacro:include filename="$(find robotic_description)/urdf/robotic.gazebo" /> -->

  <!-- ****************** ROBOT CONSTANTS *******************************  -->
  <!-- Define the siz.e of the robot's main chassis in meters -->
  <xacro:property name="base_width" value="0.160" />
  <xacro:property name="base_length" value="0.120" />
  <xacro:property name="base_height" value="0.160" />

  <!-- Define the shape of the robot's two back wheels in meters -->
  <xacro:property name="wheel_radius" value="0.035" />
  <xacro:property name="wheel_width" value="0.0124" />

  <!-- x-axis points forward, y-axis points to left, z-axis points upwards -->
  <!-- Define the gap between the wheel and chassis along y-axis in meters -->
  <xacro:property name="wheel_ygap" value="0.0" /> , <!--
  Position the wheels along the z-axis -->
  <xacro:property name="wheel_zoff" value="${0.012+wheel_radius}" />

  <!-- Position the wheels along the x-axis -->
  <xacro:property name="wheel_xoff" value="0.0" />

  <!-- Define intertial property macros  -->
  <xacro:macro name="box_inertia" params="m w h d">
    <inertial>
      <origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}" />
      <mass value="${m}" />
      <inertia ixx="${(m/12) * (h*h + d*d)}" ixy="0.0" ixz="0.0" iyy="${(m/12) * (w*w + d*d)}"
        iyz="0.0" izz="${(m/12) * (w*w + h*h)}" />
    </inertial>
  </xacro:macro>

  <xacro:macro
    name="cylinder_inertia" params="m r h">
    <inertial>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
      <mass value="${m}" />
      <inertia ixx="${(m/12) * (3*r*r + h*h)}" ixy="0" ixz="0" iyy="${(m/12) * (3*r*r + h*h)}"
        iyz="0" izz="${(m/2) * (r*r)}" />
    </inertial>
  </xacro:macro>

  <xacro:macro
    name="sphere_inertia" params="m r">
    <inertial>
      <mass value="${m}" />
      <inertia ixx="${(2/5) * m * (r*r)}" ixy="0.0" ixz="0.0" iyy="${(2/5) * m * (r*r)}" iyz="0.0"
        izz="${(2/5) * m * (r*r)}" />
    </inertial>
  </xacro:macro>

  <!-- ****************** ROBOT BASE FOOTPRINT ***************************  -->
  <!-- Define the center of the main robot chassis projected on the ground -->	
  <link name="base_footprint" />

  <!-- The base footprint of the robot is located underneath the chassis -->
  <joint
    name="base_footprint_joint" type="fixed">
    <parent link="base_link" />
    <child link="base_footprint" />
    <origin xyz="0.0 0.0 ${(wheel_radius+wheel_zoff)}" rpy="0 0 0" />
  </joint>


  <!-- ********************** ROBOT BASE *********************************  -->
  <link
    name="base_link">
    <visual>
      <origin xyz="0 0 -0.002" rpy="0 0 0" />
      <geometry>
        <cylinder length="${base_length}" radius="${base_width/2}" />
      </geometry>
      <material name="Red">
        <color rgba="1.0 0.0 0.0 1.0" />
      </material>
    </visual>

    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}" />
      </geometry>
    </collision>

    <!-- <xacro:box_inertia m="40.0" w="${base_width}" d="${base_length}" h="${base_height}" /> -->
  </link>

  <gazebo
    reference="base_link">
    <material>Gazebo/Red</material>
  </gazebo>

  <!-- *********************** DRIVE WHEELS ******************************  -->

  <xacro:macro name="wheel" params="prefix x_reflect y_reflect">
    <link name="${prefix}_link">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}" />
        </geometry>
        <material name="White">
          <color rgba="1.0 1.0 1.0 1.0" />
        </material>
      </visual>

      <collision>180
        <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}" />
        </geometry>
      </collision>

      <xacro:cylinder_inertia m="0.1" r="${wheel_radius}" h="${wheel_width}" />

    </link>

    <!-- Connect the wheels to the base_link at the appropriate location, and 
         define a continuous joint to allow the wheels to freely rotate about
         an axis -->
    <joint name="${prefix}_joint" type="continuous">
      <parent link="base_link" />
      <child link="${prefix}_link" />
      <origin xyz="${x_reflect*wheel_xoff} ${y_reflect*(base_width/2+wheel_ygap)} ${-wheel_zoff}"
        rpy="0 0 0" />
      <!-- <limit upper="3.1415" lower="-3.1415" effort="30" velocity="5.0" /> -->
      <axis xyz="0 1 0" />
    </joint>
  </xacro:macro>

  <!-- Instantiate two wheels using the macro we just made through the 
       xacro:wheel tags. We also define the parameters to have one wheel
       on both sides at the back of our robot (i.e. x_reflect=-1). -->
  <xacro:wheel prefix="left_wheel" x_reflect="0" y_reflect="1" />
  <xacro:wheel prefix="right_wheel" x_reflect="0" y_reflect="-1" />

  <!-- *********************** TEFLON ******************************  -->

  <link name="teflon">
    <visual>
      <geometry>
        <box size="0.013 0.102 0.0247"/>
      </geometry>
      <material name="White">
        <color rgba="1.0 1.0 1.0 1.0" />
      </material>
    </visual>
    <collision>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <geometry>
        <box size="0.013 0.102 0.0247"/>
      </geometry>
    </collision>
  </link>

  <joint name="teflon_joint" type="fixed">
    <parent link="base_link" />
    <child link="teflon" />
    <origin xyz="0.0 0.0 ${-(base_height/2)+0.013}" rpy="${pi/2} ${pi/2} 0" />
  </joint>

  



  <!-- *********************** CAMERA SETUP *********************************  -->
  <!-- Each sensor must be attached to a link.                              --> 
  
  <joint
    name="camera_joint" type="fixed">
    <parent link="base_link" />
    <child link="camera_link" />
    <origin xyz="-0.085 0 -0.02" rpy="0 ${pi/2} 0" />
  </joint>

  <link name="camera_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.0238 0.0238 0.00112" />
      </geometry>
      <material name="Green">
        <color rgba="0.0 1.0 0.0 1.0" />
      </material>
    </visual>
  </link>

  <!-- *********************** LIDAR SETUP **********************************  -->
  <joint
    name="laser_joint" type="fixed">
    <parent link="base_link" />
    <child link="laser" />
    <origin xyz="0 0 0.07" rpy="0 0 0" />
  </joint>

  <link name="laser">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${0.075/2}" length="0.053" />
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${0.075/2}" length="0.053" />
      </geometry>
      <material name="Black">
        <color rgba="0.0 0.0 0.0 1.0" />
      </material>
    </visual>

    <inertial>
      <mass value="0.114" />
      <origin xyz="0 0 0" rpy="0 0 0" />
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001" />
    </inertial>
  </link>

</robot>
